apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
spec:
  type: NodePort
  selector:
    name: nginx-ingress
  ports:
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
